version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ebay_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ebay_store_manager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - ebay_network

  redis:
    image: redis:7-alpine
    container_name: ebay_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ebay_network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: ebay_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/ebay_store_manager?authSource=admin
      JWT_SECRET: your_jwt_secret_here_change_in_production
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: info
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - ebay_network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: ebay_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ebay_network

volumes:
  mongodb_data:
  redis_data:

networks:
  ebay_network:
    driver: bridge
